# Generated by Django 5.0.6 on 2024-10-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='name_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
