# Generated by Django 5.0.6 on 2024-10-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_followers_customuser_follows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
