# Generated by Django 5.1.1 on 2024-10-28 14:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_bio_alter_customuser_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_pick',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path_bg),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pick',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path_profile),
        ),
    ]
