# Generated by Django 5.1.1 on 2024-12-01 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_publication_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='commented_by',
            field=models.ManyToManyField(related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
