# Generated by Django 5.1.1 on 2024-12-05 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_publication_commented_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={},
        ),
    ]
