# Generated by Django 5.1.1 on 2024-12-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_publication_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="background_pick",
            new_name="background_pic",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="is_verificated",
            new_name="is_verified",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="name_id",
            new_name="name_tag",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="profile_pick",
            new_name="profile_pick",
        ),
    ]
