# Generated by Django 5.1.1 on 2025-01-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_profile_pick_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
